"""Session-tools package — split out of the legacy session_tools.py monolith.

This ``__init__`` re-exports every public *and* private symbol that the
old session_tools.py file exposed. External callers
(``worker_hook.py``, ``type_verify.py``, ``verify_action.py``,
``tools.py``, ``orchestrator_tools``, ``antibot/captcha/solve_vision.py``,
the ``tests/`` suite) keep their ``from .session_tools import …`` lines
working unchanged.
"""

from __future__ import annotations

from .captcha_solver import _first_actionable, _solve_captcha_iterative
from .constants import (
    BLOCKED_BROWSER_OPEN_HARD_STOP,
    RESUMPTION_PATH,
    RESUMPTION_TTL_SEC,
    SCREENSHOT_DIR,
    SUPERBROWSER_URL,
    _ATOMIC_FIX_TEXT_JS,
    _CAPTCHA_KEYWORDS,
    _CONTENT_HASH_LEN,
    _CURSOR_TOOL_NAMES,
    _HARD_DOMAINS,
    _SUBMIT_KEYWORDS,
)
from .crosscheck import _dom_vision_crosscheck, _vision_dom_crosscheck
from .dom_helpers import (
    _build_network_block_message,
    _fetch_elements,
    _fetch_elements_with_bounds,
    _format_state,
    _rect_iou,
    _resolve_v_by_label,
)
from .effect import (
    _classify_effect,
    _diff_text,
    _maybe_no_effect_prefix,
    _maybe_script_usage_warning,
)
from .exceptions import WorkerMustExitError
from .http_client import (
    _T3Response,
    _auth_headers,
    _fetch_feedback_state,
    _feedback_gate,
    _is_t3_url,
    _request_with_backoff,
    _t3_dispatch_from_http,
)
from .registration import register_session_tools
from .resumption import (
    _extract_recent_failures,
    clear_resumption_artifact,
    load_resumption_artifact,
    save_resumption_artifact,
)
from .state import BrowserSessionState
from .telemetry import _compute_screenshot_budget, _update_scroll_telemetry
from .tools import (
    BrowserAskUserTool,
    BrowserBriefMarkTool,
    BrowserCaptchaScreenshotTool,
    BrowserClickAtTool,
    BrowserClickSelectorTool,
    BrowserClickTool,
    BrowserCloseTool,
    BrowserDetectCaptchaTool,
    BrowserDialogTool,
    BrowserDragPathTool,
    BrowserDragSelectorsTool,
    BrowserDragSliderUntilTool,
    BrowserDragTool,
    BrowserEscalateTool,
    BrowserEvalTool,
    BrowserFixTextAtTool,
    BrowserFormBeginTool,
    BrowserFormCommitTool,
    BrowserFormPlanTool,
    BrowserFormStatusTool,
    BrowserGetMarkdownTool,
    BrowserGetRectTool,
    BrowserImageRegionTool,
    BrowserKeysTool,
    BrowserListSliderHandlesTool,
    BrowserNavigateTool,
    BrowserOpenTool,
    BrowserPlanNextStepsTool,
    BrowserRequestHelpTool,
    BrowserRewindToCheckpointTool,
    BrowserRunScriptTool,
    BrowserScreenshotTool,
    BrowserScrollTool,
    BrowserScrollUntilTool,
    BrowserSelectOptionTool,
    BrowserSelectTool,
    BrowserSetSliderAtTool,
    BrowserSetSliderTool,
    BrowserSolveCaptchaTool,
    BrowserSolvePuzzleTool,
    BrowserTypeAtTool,
    BrowserTypeTool,
    BrowserVerifyFactTool,
    BrowserWaitForTool,
)
from .vision_sync import (
    _append_fresh_vision,
    _await_vision_prefetch,
    _await_vision_required,
    _force_fresh_vision,
    _is_captcha_intent,
    _last_vision_has_captcha_flag,
    _push_vision_bboxes,
    _push_vision_pending,
    _read_image_dims,
    _schedule_vision_prefetch,
    _vision_alternatives_hint,
)

__all__ = [
    # Public API
    "BrowserSessionState",
    "register_session_tools",
    # Public constants
    "RESUMPTION_PATH",
    "RESUMPTION_TTL_SEC",
    "SCREENSHOT_DIR",
    "SUPERBROWSER_URL",
    "WorkerMustExitError",
    # Public resumption helpers
    "clear_resumption_artifact",
    "load_resumption_artifact",
    "save_resumption_artifact",
    # Tool classes (44)
    "BrowserAskUserTool",
    "BrowserBriefMarkTool",
    "BrowserCaptchaScreenshotTool",
    "BrowserClickAtTool",
    "BrowserClickSelectorTool",
    "BrowserClickTool",
    "BrowserCloseTool",
    "BrowserDetectCaptchaTool",
    "BrowserDialogTool",
    "BrowserDragPathTool",
    "BrowserDragSelectorsTool",
    "BrowserDragSliderUntilTool",
    "BrowserDragTool",
    "BrowserEscalateTool",
    "BrowserEvalTool",
    "BrowserFixTextAtTool",
    "BrowserFormBeginTool",
    "BrowserFormCommitTool",
    "BrowserFormPlanTool",
    "BrowserFormStatusTool",
    "BrowserGetMarkdownTool",
    "BrowserGetRectTool",
    "BrowserImageRegionTool",
    "BrowserKeysTool",
    "BrowserListSliderHandlesTool",
    "BrowserNavigateTool",
    "BrowserOpenTool",
    "BrowserPlanNextStepsTool",
    "BrowserRequestHelpTool",
    "BrowserRewindToCheckpointTool",
    "BrowserRunScriptTool",
    "BrowserScreenshotTool",
    "BrowserScrollTool",
    "BrowserScrollUntilTool",
    "BrowserSelectOptionTool",
    "BrowserSelectTool",
    "BrowserSetSliderAtTool",
    "BrowserSetSliderTool",
    "BrowserSolveCaptchaTool",
    "BrowserSolvePuzzleTool",
    "BrowserTypeAtTool",
    "BrowserTypeTool",
    "BrowserVerifyFactTool",
    "BrowserWaitForTool",
    # Private constants used by other modules / tests
    "BLOCKED_BROWSER_OPEN_HARD_STOP",
    "_ATOMIC_FIX_TEXT_JS",
    "_CAPTCHA_KEYWORDS",
    "_CONTENT_HASH_LEN",
    "_CURSOR_TOOL_NAMES",
    "_HARD_DOMAINS",
    "_SUBMIT_KEYWORDS",
    # Private helpers used by other modules / tests
    "_T3Response",
    "_append_fresh_vision",
    "_auth_headers",
    "_await_vision_prefetch",
    "_await_vision_required",
    "_build_network_block_message",
    "_classify_effect",
    "_compute_screenshot_budget",
    "_diff_text",
    "_dom_vision_crosscheck",
    "_extract_recent_failures",
    "_fetch_elements",
    "_fetch_elements_with_bounds",
    "_fetch_feedback_state",
    "_first_actionable",
    "_force_fresh_vision",
    "_format_state",
    "_is_captcha_intent",
    "_is_t3_url",
    "_last_vision_has_captcha_flag",
    "_maybe_no_effect_prefix",
    "_maybe_script_usage_warning",
    "_push_vision_bboxes",
    "_push_vision_pending",
    "_read_image_dims",
    "_rect_iou",
    "_request_with_backoff",
    "_resolve_v_by_label",
    "_schedule_vision_prefetch",
    "_solve_captcha_iterative",
    "_t3_dispatch_from_http",
    "_update_scroll_telemetry",
    "_vision_alternatives_hint",
    "_vision_dom_crosscheck",
    "_feedback_gate",
]
